/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AssetId = string;
export interface BotSettings {
  'targetAssets' : Array<AssetId>,
  'enabled' : boolean,
  'dipThresholdPercent' : number,
}
export interface RecurringBuyRule {
  'assetId' : AssetId,
  'intervalDays' : bigint,
  'enabled' : boolean,
  'assetName' : string,
  'amountUsd' : number,
}
export interface Trade {
  'tradeType' : string,
  'assetId' : AssetId,
  'note' : string,
  'timestamp' : number,
  'quantity' : number,
  'assetName' : string,
  'priceUsd' : number,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createRecurringBuyRule' : ActorMethod<[RecurringBuyRule], undefined>,
  'createTrade' : ActorMethod<[Trade], undefined>,
  'deleteRecurringBuyRule' : ActorMethod<[AssetId], undefined>,
  'deleteTrade' : ActorMethod<[AssetId], undefined>,
  'fetchCoinDetails' : ActorMethod<[AssetId], string>,
  'fetchCoinHistory' : ActorMethod<[AssetId, bigint], string>,
  'fetchPrices' : ActorMethod<[Array<AssetId>], string>,
  'fetchTopCoins' : ActorMethod<[], string>,
  'getBotSettings' : ActorMethod<[Principal], [] | [BotSettings]>,
  'getCallerBotSettings' : ActorMethod<[], [] | [BotSettings]>,
  'getCallerRecurringBuyRules' : ActorMethod<[], Array<RecurringBuyRule>>,
  'getCallerTrades' : ActorMethod<[], Array<Trade>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getTrades' : ActorMethod<[Principal], Array<Trade>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateBotSettings' : ActorMethod<[BotSettings], undefined>,
  'updateRecurringBuyRule' : ActorMethod<
    [AssetId, RecurringBuyRule],
    undefined
  >,
  'updateTrade' : ActorMethod<[AssetId, Trade], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];