/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AssetId = IDL.Text;
export const RecurringBuyRule = IDL.Record({
  'assetId' : AssetId,
  'intervalDays' : IDL.Nat,
  'enabled' : IDL.Bool,
  'assetName' : IDL.Text,
  'amountUsd' : IDL.Float64,
});
export const Trade = IDL.Record({
  'tradeType' : IDL.Text,
  'assetId' : AssetId,
  'note' : IDL.Text,
  'timestamp' : IDL.Float64,
  'quantity' : IDL.Float64,
  'assetName' : IDL.Text,
  'priceUsd' : IDL.Float64,
});
export const BotSettings = IDL.Record({
  'targetAssets' : IDL.Vec(AssetId),
  'enabled' : IDL.Bool,
  'dipThresholdPercent' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createRecurringBuyRule' : IDL.Func([RecurringBuyRule], [], []),
  'createTrade' : IDL.Func([Trade], [], []),
  'deleteRecurringBuyRule' : IDL.Func([AssetId], [], []),
  'deleteTrade' : IDL.Func([AssetId], [], []),
  'fetchCoinDetails' : IDL.Func([AssetId], [IDL.Text], []),
  'fetchCoinHistory' : IDL.Func([AssetId, IDL.Nat], [IDL.Text], []),
  'fetchPrices' : IDL.Func([IDL.Vec(AssetId)], [IDL.Text], []),
  'fetchTopCoins' : IDL.Func([], [IDL.Text], []),
  'getBotSettings' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(BotSettings)],
      ['query'],
    ),
  'getCallerBotSettings' : IDL.Func([], [IDL.Opt(BotSettings)], ['query']),
  'getCallerRecurringBuyRules' : IDL.Func(
      [],
      [IDL.Vec(RecurringBuyRule)],
      ['query'],
    ),
  'getCallerTrades' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getTrades' : IDL.Func([IDL.Principal], [IDL.Vec(Trade)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateBotSettings' : IDL.Func([BotSettings], [], []),
  'updateRecurringBuyRule' : IDL.Func([AssetId, RecurringBuyRule], [], []),
  'updateTrade' : IDL.Func([AssetId, Trade], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AssetId = IDL.Text;
  const RecurringBuyRule = IDL.Record({
    'assetId' : AssetId,
    'intervalDays' : IDL.Nat,
    'enabled' : IDL.Bool,
    'assetName' : IDL.Text,
    'amountUsd' : IDL.Float64,
  });
  const Trade = IDL.Record({
    'tradeType' : IDL.Text,
    'assetId' : AssetId,
    'note' : IDL.Text,
    'timestamp' : IDL.Float64,
    'quantity' : IDL.Float64,
    'assetName' : IDL.Text,
    'priceUsd' : IDL.Float64,
  });
  const BotSettings = IDL.Record({
    'targetAssets' : IDL.Vec(AssetId),
    'enabled' : IDL.Bool,
    'dipThresholdPercent' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createRecurringBuyRule' : IDL.Func([RecurringBuyRule], [], []),
    'createTrade' : IDL.Func([Trade], [], []),
    'deleteRecurringBuyRule' : IDL.Func([AssetId], [], []),
    'deleteTrade' : IDL.Func([AssetId], [], []),
    'fetchCoinDetails' : IDL.Func([AssetId], [IDL.Text], []),
    'fetchCoinHistory' : IDL.Func([AssetId, IDL.Nat], [IDL.Text], []),
    'fetchPrices' : IDL.Func([IDL.Vec(AssetId)], [IDL.Text], []),
    'fetchTopCoins' : IDL.Func([], [IDL.Text], []),
    'getBotSettings' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(BotSettings)],
        ['query'],
      ),
    'getCallerBotSettings' : IDL.Func([], [IDL.Opt(BotSettings)], ['query']),
    'getCallerRecurringBuyRules' : IDL.Func(
        [],
        [IDL.Vec(RecurringBuyRule)],
        ['query'],
      ),
    'getCallerTrades' : IDL.Func([], [IDL.Vec(Trade)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getTrades' : IDL.Func([IDL.Principal], [IDL.Vec(Trade)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateBotSettings' : IDL.Func([BotSettings], [], []),
    'updateRecurringBuyRule' : IDL.Func([AssetId, RecurringBuyRule], [], []),
    'updateTrade' : IDL.Func([AssetId, Trade], [], []),
  });
};

export const init = ({ IDL }) => { return []; };